joint_limits:
  joint2_1:
    has_velocity_limits: true
    max_velocity: 2.26
    has_acceleration_limits: true
    max_acceleration: 0.452
  joint4_1:
    has_velocity_limits: true
    max_velocity: 2.96
    has_acceleration_limits: true
    max_acceleration: 0.592
  joint3_1:
    has_velocity_limits: true
    max_velocity: 2.96
    has_acceleration_limits: true
    max_acceleration: 0.592
  joint1_1:
    has_velocity_limits: true
    max_velocity: 2.26
    has_acceleration_limits: true
    max_acceleration: 0.452
  joint5_1:
    has_velocity_limits: true
    max_velocity: 3.48
    has_acceleration_limits: true
    max_acceleration: 0.696
  joint1_2:
    has_velocity_limits: true
    max_velocity: 2.26
    has_acceleration_limits: true
    max_acceleration: 0.452
  joint6_1:
    has_velocity_limits: true
    max_velocity: 3.48
    has_acceleration_limits: true
    max_acceleration: 0.696
  joint5_2:
    has_velocity_limits: true
    max_velocity: 3.48
    has_acceleration_limits: true
    max_acceleration: 0.696
  joint6_2:
    has_velocity_limits: true
    max_velocity: 3.48
    has_acceleration_limits: true
    max_acceleration: 0.696
  joint2_2:
    has_velocity_limits: true
    max_velocity: 2.26
    has_acceleration_limits: true
    max_acceleration: 0.452
  joint3_2:
    has_velocity_limits: true
    max_velocity: 2.96
    has_acceleration_limits: true
    max_acceleration: 0.592
  joint4_2:
    has_velocity_limits: true
    max_velocity: 2.96
    has_acceleration_limits: true
    max_acceleration: 0.592